import {cn} from '@/lib/utils'
import type {Metadata} from 'next'
import {ThemeProvider} from 'next-themes'
import {Inter, JetBrains_Mono} from 'next/font/google'
import {Toaster} from 'sonner'
import {Header} from '../components/header'
import './globals.css'

const inter = Inter({subsets: ['latin'], variable: '--font-sans'})
const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
})

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html
      lang="en"
      className={cn(inter.variable, jetBrainsMono.variable)}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
